/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.petshopinventorycontrol.employee.view;

import com.toedter.calendar.JDateChooser;
import utils.MongoConnection;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.FindOneAndUpdateOptions;
import com.mongodb.client.model.ReturnDocument;
import com.mongodb.client.model.Updates;

import org.bson.Document;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import com.mongodb.client.model.Sorts;

/**
 *
 * @author Steven Loza @ESPE
 */
public class FrmSupplier extends javax.swing.JFrame {

    private MongoDatabase db;
    private MongoCollection<Document> colSuppliers;

    private String currentSupplierId = null;
    private boolean currentIdCommitted = false;

    private final Color COLOR_OK = Color.WHITE;
    private final Color COLOR_ERROR = new Color(255, 200, 200);

    /**
     * Creates new form FrmSupplier
     */
    public FrmSupplier() {

        initComponents();

        initMongo();

        txtIdSupplier.setEditable(false);
        txtIdSupplier.setEnabled(true);
        txtIdSupplier.setBackground(new Color(240, 240, 240));

        setupInputFilters();

        currentSupplierId = getNextAvailableSupplierId();
        currentIdCommitted = false;
        txtIdSupplier.setText(currentSupplierId);

        currentIdCommitted = false;
        txtIdSupplier.setText(currentSupplierId);

//        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem1ActionPerformed(evt);
//            }
//        });
//
//        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem2ActionPerformed(evt);
//            }
//        });
//
//        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem3ActionPerformed(evt);
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnbacksupplier = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdSupplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTypeSupplier = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhoneSupplier = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPhone2Supplier = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNameSupplier = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCitySupplier = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStateSupplier = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEnterpriselSupplier = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtemailSupplier = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jDateEntry = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuFile = new javax.swing.JMenu();
        itmNewRegisterSupplier = new javax.swing.JMenuItem();
        itmDeleteRegisterSupplier = new javax.swing.JMenuItem();
        itmSaveRegisterSupplier = new javax.swing.JMenuItem();
        itmDuplicateRegisterSupplier = new javax.swing.JMenuItem();
        MnuOptions = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MnuHelp = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 119));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROVEEDORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 119));

        btnbacksupplier.setText("Regresar");
        btnbacksupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacksupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnbacksupplier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnbacksupplier)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel2.setText("Id proveedor:");

        txtIdSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSupplierActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel3.setText("Tipo de proveedor:");

        txtTypeSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeSupplierActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel4.setText("Telefono Contacto:");

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel5.setText("Telefono 2:");

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel6.setText("Nombre Contacto:");

        txtNameSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameSupplierActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel7.setText("Ciudad:");

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel8.setText("Provincia:");

        txtStateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateSupplierActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel9.setText("Empresa:");

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel11.setText("Correo electronico:");

        txtemailSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailSupplierActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel10.setText("Fecha de ingreso: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTypeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPhoneSupplier))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNameSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPhone2Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCitySupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStateSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnterpriselSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemailSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTypeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPhoneSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhone2Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNameSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCitySupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtStateSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEnterpriselSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtemailSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jDateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        MnuFile.setText("Archivo");

        itmNewRegisterSupplier.setText("Nuevo Registro");
        itmNewRegisterSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmNewRegisterSupplierActionPerformed(evt);
            }
        });
        MnuFile.add(itmNewRegisterSupplier);

        itmDeleteRegisterSupplier.setText("Borrar Registro");
        itmDeleteRegisterSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDeleteRegisterSupplierActionPerformed(evt);
            }
        });
        MnuFile.add(itmDeleteRegisterSupplier);

        itmSaveRegisterSupplier.setText("Guardar Registro");
        itmSaveRegisterSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSaveRegisterSupplierActionPerformed(evt);
            }
        });
        MnuFile.add(itmSaveRegisterSupplier);

        itmDuplicateRegisterSupplier.setText("Duplicar Registro");
        itmDuplicateRegisterSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDuplicateRegisterSupplierActionPerformed(evt);
            }
        });
        MnuFile.add(itmDuplicateRegisterSupplier);

        jMenuBar1.add(MnuFile);

        MnuOptions.setText("Opciones");

        jMenuItem1.setText("Grafica Proveedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnuOptions.add(jMenuItem1);

        jMenuItem2.setText("Informe Proveedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MnuOptions.add(jMenuItem2);

        jMenuBar1.add(MnuOptions);

        MnuHelp.setText("Ayuda");

        jMenuItem3.setText("Información");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MnuHelp.add(jMenuItem3);

        jMenuBar1.add(MnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSupplierActionPerformed

    private void txtNameSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameSupplierActionPerformed

    private void txtStateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateSupplierActionPerformed

    private void txtemailSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailSupplierActionPerformed

    private void itmNewRegisterSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmNewRegisterSupplierActionPerformed
        newRegister();
    }//GEN-LAST:event_itmNewRegisterSupplierActionPerformed

    private void itmDeleteRegisterSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDeleteRegisterSupplierActionPerformed
        deleteRegisterUIOnly();
    }//GEN-LAST:event_itmDeleteRegisterSupplierActionPerformed

    private void itmSaveRegisterSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSaveRegisterSupplierActionPerformed
        saveSupplierToMongo();
    }//GEN-LAST:event_itmSaveRegisterSupplierActionPerformed

    private void itmDuplicateRegisterSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDuplicateRegisterSupplierActionPerformed
        duplicateRegister();
    }//GEN-LAST:event_itmDuplicateRegisterSupplierActionPerformed

    private void txtTypeSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeSupplierActionPerformed

    private void btnbacksupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacksupplierActionPerformed
        // new FrmEmployeeMenu().setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_btnbacksupplierActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        // Ejemplo (cuando tengas la clase):
        // new FrmSupplierChart().setVisible(true);
        // this.dispose();
        JOptionPane.showMessageDialog(this,
                "Pendiente: abrir ventana de Gráfica de Proveedores.",
                "Navegación", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Ejemplo (cuando tengas la clase):
        // new FrmSupplierReport().setVisible(true);
        // this.dispose();

        JOptionPane.showMessageDialog(this,
                "Pendiente: abrir ventana de Informe de Proveedores.",
                "Navegación", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        String info
                = "Información\n"
                + "El módulo de proveedores permite gestionar y organizar la información relacionada con las entidades que suministran productos o servicios al sistema. "
                + "Desde esta sección se pueden registrar, consultar y actualizar datos clave que facilitan la integración con otros procesos. "
                + "Su uso contribuye a mantener la información ordenada y coherente dentro del sistema.";

        JTextArea textArea = new JTextArea(info);
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        textArea.setEditable(false);
        textArea.setCaretPosition(0);

        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(520, 180));

        JOptionPane.showMessageDialog(this, scrollPane, "Información", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void initMongo() {
        db = MongoConnection.getDatabase();
        colSuppliers = db.getCollection("suppliers");

    }

    private String getNextAvailableSupplierId() {
        String dateKey = new SimpleDateFormat("ddMMyy").format(new Date());

        Document last = colSuppliers.find(Filters.regex("idSupplier", "^" + dateKey + "-"))
                .sort(Sorts.descending("idSupplier"))
                .limit(1)
                .first();

        int nextSeq = 1;

        if (last != null) {
            String lastId = last.getString("idSupplier");
            if (lastId != null && lastId.contains("-")) {
                try {
                    int lastSeq = Integer.parseInt(lastId.split("-")[1]);
                    nextSeq = lastSeq + 1;
                } catch (Exception ignored) {
                    nextSeq = 1;
                }
            }
        }

        return String.format("%s-%03d", dateKey, nextSeq);
    }

    private void clearEditableFields() {
        txtTypeSupplier.setText("");
        txtPhoneSupplier.setText("");
        txtPhone2Supplier.setText("");
        txtNameSupplier.setText("");
        txtCitySupplier.setText("");
        txtStateSupplier.setText("");
        txtEnterpriselSupplier.setText("");
        txtemailSupplier.setText("");
        jDateEntry.setDate(null);

        resetFieldStyle(txtTypeSupplier);
        resetFieldStyle(txtPhoneSupplier);
        resetFieldStyle(txtPhone2Supplier);
        resetFieldStyle(txtNameSupplier);
        resetFieldStyle(txtCitySupplier);
        resetFieldStyle(txtStateSupplier);
        resetFieldStyle(txtEnterpriselSupplier);
        resetFieldStyle(txtemailSupplier);

    }

    private void markFieldError(JTextField field) {
        field.setBackground(COLOR_ERROR);
        field.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
    }

    private void resetFieldStyle(JTextField field) {
        field.setBackground(COLOR_OK);
        field.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 1));
    }

    private boolean validateSupplierForm() {
        boolean ok = true;

        resetFieldStyle(txtTypeSupplier);
        resetFieldStyle(txtPhoneSupplier);
        resetFieldStyle(txtPhone2Supplier);
        resetFieldStyle(txtNameSupplier);
        resetFieldStyle(txtCitySupplier);
        resetFieldStyle(txtStateSupplier);
        resetFieldStyle(txtEnterpriselSupplier);
        resetFieldStyle(txtemailSupplier);

        if (txtTypeSupplier.getText().trim().isEmpty()) {
            markFieldError(txtTypeSupplier);
            ok = false;
        }
        if (txtPhoneSupplier.getText().trim().isEmpty()) {
            markFieldError(txtPhoneSupplier);
            ok = false;
        }
        if (txtPhone2Supplier.getText().trim().isEmpty()) {
            markFieldError(txtPhone2Supplier);
            ok = false;
        }
        if (txtNameSupplier.getText().trim().isEmpty()) {
            markFieldError(txtNameSupplier);
            ok = false;
        }
        if (txtCitySupplier.getText().trim().isEmpty()) {
            markFieldError(txtCitySupplier);
            ok = false;
        }
        if (txtStateSupplier.getText().trim().isEmpty()) {
            markFieldError(txtStateSupplier);
            ok = false;
        }
        if (txtEnterpriselSupplier.getText().trim().isEmpty()) {
            markFieldError(txtEnterpriselSupplier);
            ok = false;
        }
        if (txtemailSupplier.getText().trim().isEmpty()) {
            markFieldError(txtemailSupplier);
            ok = false;
        }
        if (jDateEntry.getDate() == null) {
            ok = false;
        }

        if (!txtPhoneSupplier.getText().matches("^\\d{12}$")) {
            markFieldError(txtPhoneSupplier);
            ok = false;
        }
        if (!txtPhone2Supplier.getText().matches("^\\d{12}$")) {
            markFieldError(txtPhone2Supplier);
            ok = false;
        }

        String email = txtemailSupplier.getText().trim();
        if (!email.matches("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}(.{0,})?$")) {
            markFieldError(txtemailSupplier);
            ok = false;
        }

        if (!ok) {
            String extra = (jDateEntry.getDate() == null) ? "\n- Falta la fecha de ingreso." : "";
            JOptionPane.showMessageDialog(this,
                    "Revisa los campos en rojo. No se puede guardar." + extra,
                    "Validación", JOptionPane.WARNING_MESSAGE);
        }

        return ok;
    }

    private Document buildSupplierDocument() {
        return new Document("idSupplier", currentSupplierId)
                .append("typeSupplier", txtTypeSupplier.getText().trim())
                .append("phoneSupplier", txtPhoneSupplier.getText().trim())
                .append("phone2Supplier", txtPhone2Supplier.getText().trim())
                .append("nameSupplier", txtNameSupplier.getText().trim())
                .append("citySupplier", txtCitySupplier.getText().trim())
                .append("stateSupplier", txtStateSupplier.getText().trim())
                .append("enterpriseSupplier", txtEnterpriselSupplier.getText().trim())
                .append("emailSupplier", txtemailSupplier.getText().trim())
                .append("entryDate", jDateEntry.getDate());
    }

    private void saveSupplierToMongo() {
        if (!validateSupplierForm()) {
            return;
        }

        try {

            Document exists = colSuppliers.find(Filters.eq("idSupplier", currentSupplierId)).first();
            if (exists != null) {
                currentSupplierId = getNextAvailableSupplierId();
                txtIdSupplier.setText(currentSupplierId);

                JOptionPane.showMessageDialog(this,
                        "El ID ya estaba ocupado. Se asignó uno nuevo: " + currentSupplierId,
                        "ID Actualizado", JOptionPane.WARNING_MESSAGE);
            }

            colSuppliers.insertOne(buildSupplierDocument());
            currentIdCommitted = true;

            JOptionPane.showMessageDialog(this,
                    "Proveedor guardado ✅\nID: " + currentSupplierId,
                    "OK", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar en MongoDB: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void newRegister() {
        clearEditableFields();

        if (currentIdCommitted) {

            currentIdCommitted = false;
        }
        txtIdSupplier.setText(currentSupplierId);
    }

    private void deleteRegisterUIOnly() {
        clearEditableFields();

        txtIdSupplier.setText(currentSupplierId);
    }

    private void duplicateRegister() {

        if (isAllEditableFieldsEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay datos para duplicar. Primero llena los campos.",
                    "Duplicar", JOptionPane.WARNING_MESSAGE);
            return;
        }

        currentSupplierId = getNextAvailableSupplierId();
        currentIdCommitted = false;
        txtIdSupplier.setText(currentSupplierId);

        JOptionPane.showMessageDialog(this,
                "Datos duplicados. Nuevo ID asignado: " + currentSupplierId,
                "Duplicar", JOptionPane.INFORMATION_MESSAGE);
    }

    private boolean isAllEditableFieldsEmpty() {
        boolean textEmpty
                = txtTypeSupplier.getText().trim().isEmpty()
                && txtPhoneSupplier.getText().trim().isEmpty()
                && txtPhone2Supplier.getText().trim().isEmpty()
                && txtNameSupplier.getText().trim().isEmpty()
                && txtCitySupplier.getText().trim().isEmpty()
                && txtStateSupplier.getText().trim().isEmpty()
                && txtEnterpriselSupplier.getText().trim().isEmpty()
                && txtemailSupplier.getText().trim().isEmpty();

        boolean dateEmpty = (jDateEntry.getDate() == null);

        return textEmpty && dateEmpty;
    }

    private void setupInputFilters() {

        setTextFilter(txtTypeSupplier, 50);
        setTextFilter(txtNameSupplier, 50);
        setTextFilter(txtCitySupplier, 50);
        setTextFilter(txtStateSupplier, 50);
        setTextFilter(txtEnterpriselSupplier, 50);

        setNumericFilter(txtPhoneSupplier, 12);
        setNumericFilter(txtPhone2Supplier, 12);

        setEmailFilter(txtemailSupplier, 80);
    }

    private void setTextFilter(JTextField field, int max) {
        ((AbstractDocument) field.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                if (text == null) {
                    return;
                }

                String current = fb.getDocument().getText(0, fb.getDocument().getLength());
                String next = current.substring(0, offset) + text + current.substring(offset + length);

                if (!text.matches("[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s]*")) {
                    return;
                }
                if (next.length() <= max) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }

    private void setNumericFilter(JTextField field, int max) {
        ((AbstractDocument) field.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                if (text == null) {
                    return;
                }

                if (!text.matches("\\d*")) {
                    return;
                }

                String current = fb.getDocument().getText(0, fb.getDocument().getLength());
                String next = current.substring(0, offset) + text + current.substring(offset + length);

                if (next.length() <= max) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
    }

    private void setEmailFilter(JTextField field, int max) {
        ((AbstractDocument) field.getDocument()).setDocumentFilter(new DocumentFilter() {
            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                    throws BadLocationException {
                if (text == null) {
                    return;
                }

                String current = fb.getDocument().getText(0, fb.getDocument().getLength());
                String next = current.substring(0, offset) + text + current.substring(offset + length);

                if (next.length() > max) {
                    return;
                }

                if (!text.matches("[A-Za-z0-9@._%+\\-]*")) {
                    return;
                }

                super.replace(fb, offset, length, text, attrs);
            }
        });
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuFile;
    private javax.swing.JMenu MnuHelp;
    private javax.swing.JMenu MnuOptions;
    private javax.swing.JButton btnbacksupplier;
    private javax.swing.JMenuItem itmDeleteRegisterSupplier;
    private javax.swing.JMenuItem itmDuplicateRegisterSupplier;
    private javax.swing.JMenuItem itmNewRegisterSupplier;
    private javax.swing.JMenuItem itmSaveRegisterSupplier;
    private com.toedter.calendar.JDateChooser jDateEntry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCitySupplier;
    private javax.swing.JTextField txtEnterpriselSupplier;
    private javax.swing.JTextField txtIdSupplier;
    private javax.swing.JTextField txtNameSupplier;
    private javax.swing.JTextField txtPhone2Supplier;
    private javax.swing.JTextField txtPhoneSupplier;
    private javax.swing.JTextField txtStateSupplier;
    private javax.swing.JTextField txtTypeSupplier;
    private javax.swing.JTextField txtemailSupplier;
    // End of variables declaration//GEN-END:variables
}
