package ec.edu.espe.petshopinventorycontrol.employee.sale;


/**
 *
 * @author Bryan Gudino, KNOWLEDGE ENCAPSULATE, @ESPE
 */
public class FrmEmployeeAddProduct extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEmployeeAddProduct.class.getName());
        
    /**
     * Creates new form NewJFrame9
     */
    public FrmEmployeeAddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblProduct = new javax.swing.JLabel();
        radProductAccesory = new javax.swing.JRadioButton();
        radProductToy = new javax.swing.JRadioButton();
        radProductFood = new javax.swing.JRadioButton();
        lblAnimal = new javax.swing.JLabel();
        btnBackMenuEmployee = new javax.swing.JButton();
        ComboBoxMakeDog = new javax.swing.JComboBox<>();
        lblRegisterMake = new javax.swing.JLabel();
        radProductToy1 = new javax.swing.JRadioButton();
        radProductFood1 = new javax.swing.JRadioButton();
        radProductAccesory1 = new javax.swing.JRadioButton();
        lblAnimal1 = new javax.swing.JLabel();
        radProductToy2 = new javax.swing.JRadioButton();
        radProductFood2 = new javax.swing.JRadioButton();
        radProductAccesory2 = new javax.swing.JRadioButton();
        radProductToy3 = new javax.swing.JRadioButton();
        ComboBoxMakeConejillo = new javax.swing.JComboBox<>();
        ComboBoxMakeCat = new javax.swing.JComboBox<>();
        ComboBoxRaceConejillo = new javax.swing.JComboBox<>();
        ComboBoxRaceCat = new javax.swing.JComboBox<>();
        ComboBoxRaceDog = new javax.swing.JComboBox<>();
        lblRegisterMake1 = new javax.swing.JLabel();
        ComboBoxFlavorCat = new javax.swing.JComboBox<>();
        ComboBoxFlavorDog = new javax.swing.JComboBox<>();
        lblRegisterMake2 = new javax.swing.JLabel();
        ComboBoxMakePig = new javax.swing.JComboBox<>();
        ComboBoxMakeChicken = new javax.swing.JComboBox<>();
        ComboBoxMakeCow = new javax.swing.JComboBox<>();
        lblRegisterMake3 = new javax.swing.JLabel();
        ComboBoxMakeHorse = new javax.swing.JComboBox<>();
        lblAnimal2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAnimal3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        lblAnimal4 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        lblAnimal5 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        lblAnimal6 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jSpinner12 = new javax.swing.JSpinner();
        lblAnimal8 = new javax.swing.JLabel();
        lblAnimal9 = new javax.swing.JLabel();
        ComboBoxAccesoryConejillo = new javax.swing.JComboBox<>();
        ComboBoxAccesoryCat = new javax.swing.JComboBox<>();
        jSpinner14 = new javax.swing.JSpinner();
        jSpinner16 = new javax.swing.JSpinner();
        ComboBoxAccesoryDog = new javax.swing.JComboBox<>();
        radProductToy5 = new javax.swing.JRadioButton();
        radProductFood4 = new javax.swing.JRadioButton();
        lblProduct1 = new javax.swing.JLabel();
        radProductAccesory3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        lblAnimal10 = new javax.swing.JLabel();
        ComboBoxAccesoryFarm = new javax.swing.JComboBox<>();
        lblRegisterMake4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAnimal7 = new javax.swing.JLabel();
        jSpinner15 = new javax.swing.JSpinner();
        lblAnimal14 = new javax.swing.JLabel();
        lblAnimal15 = new javax.swing.JLabel();
        lblRegisterMake5 = new javax.swing.JLabel();
        lblAnimal16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ComboBoxToyCat = new javax.swing.JComboBox<>();
        radProductAccesory4 = new javax.swing.JRadioButton();
        lblProduct2 = new javax.swing.JLabel();
        jSpinner17 = new javax.swing.JSpinner();
        lblAnimal11 = new javax.swing.JLabel();
        radProductFood5 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        lblAnimal12 = new javax.swing.JLabel();
        lblAnimal13 = new javax.swing.JLabel();
        ComboBoxToyDog = new javax.swing.JComboBox<>();
        jSpinner19 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 119));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENÚ EMPLEADO (Agregar producto a la tienda)");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setMaximumSize(new java.awt.Dimension(700, 32767));
        jPanel3.setPreferredSize(new java.awt.Dimension(630, 60));

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPrint.setText("Imprimir");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnSave)
                .addGap(63, 63, 63)
                .addComponent(btnPrint)
                .addGap(71, 71, 71)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrint)
                        .addComponent(btnDelete)))
                .addContainerGap())
        );

        lblProduct.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblProduct.setText("SECCION DE COMIDA");

        radProductAccesory.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductAccesory.setText("ACCESORIOS");
        radProductAccesory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductAccesoryActionPerformed(evt);
            }
        });

        radProductToy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductToy.setText("JUGUETE");
        radProductToy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductToyActionPerformed(evt);
            }
        });

        radProductFood.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductFood.setText("COMIDA");
        radProductFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductFoodActionPerformed(evt);
            }
        });

        lblAnimal.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal.setText("Mascotas de casa:");

        btnBackMenuEmployee.setText("Regresar al menú empleado");
        btnBackMenuEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMenuEmployeeActionPerformed(evt);
            }
        });

        ComboBoxMakeDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DogChown", "ProCat", "Michu", "Caballito", "Chanchito", "Balanceado" }));
        ComboBoxMakeDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMakeDogActionPerformed(evt);
            }
        });

        lblRegisterMake.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRegisterMake.setText("Marcas:");

        radProductToy1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductToy1.setText("Conejillo");
        radProductToy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductToy1ActionPerformed(evt);
            }
        });

        radProductFood1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductFood1.setText("Perro");
        radProductFood1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductFood1ActionPerformed(evt);
            }
        });

        radProductAccesory1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductAccesory1.setText("Gato");
        radProductAccesory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductAccesory1ActionPerformed(evt);
            }
        });

        lblAnimal1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal1.setText("De granja:");

        radProductToy2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductToy2.setText("Cerdo");
        radProductToy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductToy2ActionPerformed(evt);
            }
        });

        radProductFood2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductFood2.setText("Vaca");
        radProductFood2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductFood2ActionPerformed(evt);
            }
        });

        radProductAccesory2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductAccesory2.setText("Caballo");
        radProductAccesory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductAccesory2ActionPerformed(evt);
            }
        });

        radProductToy3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductToy3.setText("Pollo");

        ComboBoxMakeConejillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crecimiento", "Engorde" }));
        ComboBoxMakeConejillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMakeConejilloActionPerformed(evt);
            }
        });

        ComboBoxMakeCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ProCat", "Michu", "Whiskas" }));
        ComboBoxMakeCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMakeCatActionPerformed(evt);
            }
        });

        ComboBoxRaceConejillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conejo", "Hamster", "Cuy" }));
        ComboBoxRaceConejillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRaceConejilloActionPerformed(evt);
            }
        });

        ComboBoxRaceCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gatito", "Adulto", "Senior" }));
        ComboBoxRaceCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRaceCatActionPerformed(evt);
            }
        });

        ComboBoxRaceDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande/Mediano", "Pequeño" }));
        ComboBoxRaceDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRaceDogActionPerformed(evt);
            }
        });

        lblRegisterMake1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRegisterMake1.setText("Raza:");

        ComboBoxFlavorCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sardina", "Pollo", "Carne" }));
        ComboBoxFlavorCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFlavorCatActionPerformed(evt);
            }
        });

        ComboBoxFlavorDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pollo", "Carne", "Premium" }));
        ComboBoxFlavorDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFlavorDogActionPerformed(evt);
            }
        });

        lblRegisterMake2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRegisterMake2.setText("Sabor:");

        ComboBoxMakePig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cerdo crecedor", "Cerdo engorde", "Morochillo entero", "Morochillo partido", "Morochillo vitaminizado", "Moyuelo", "Sal en grano" }));
        ComboBoxMakePig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMakePigActionPerformed(evt);
            }
        });

        ComboBoxMakeChicken.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Balvit crecimiento", "Gran ave engorde", "Morochillo entero", "Morochillo partido ", "Morochillo vitaminizado", "Moyuelo", "Sal en grano" }));
        ComboBoxMakeChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMakeChickenActionPerformed(evt);
            }
        });

        ComboBoxMakeCow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morochillo entero", "Morochillo partido", "Morochillo vitaminizado", "Moyuelo", "Sal en grano" }));
        ComboBoxMakeCow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMakeCowActionPerformed(evt);
            }
        });

        lblRegisterMake3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRegisterMake3.setText("Balanceado:");

        ComboBoxMakeHorse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morochillo entero", "Morochillo partido", "Morochillo vitaminizado", "Moyuelo", "Sal en grano" }));
        ComboBoxMakeHorse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMakeHorseActionPerformed(evt);
            }
        });

        lblAnimal2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal2.setText("Valor a cancelar:");

        jLabel2.setText("$");

        lblAnimal3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal3.setText("Kilos:");

        lblAnimal4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal4.setText("Unidades:");

        jLabel3.setText("$");

        lblAnimal5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal5.setText("Valor a cancelar:");

        lblAnimal6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal6.setText("Unidades:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblProduct)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(radProductAccesory)
                        .addGap(55, 55, 55)
                        .addComponent(radProductToy)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(radProductFood)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackMenuEmployee))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblAnimal5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radProductFood2)
                                    .addComponent(radProductAccesory2)
                                    .addComponent(radProductToy2)
                                    .addComponent(radProductToy3)
                                    .addComponent(lblAnimal1)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblRegisterMake3)
                                            .addComponent(ComboBoxMakePig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBoxMakeChicken, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBoxMakeHorse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBoxMakeCow, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAnimal6)
                                        .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(290, 290, 290))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAnimal)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radProductAccesory1)
                                        .addComponent(radProductFood1))
                                    .addGap(21, 21, 21)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(radProductToy1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ComboBoxMakeDog, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBoxMakeCat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ComboBoxMakeConejillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboBoxRaceDog, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxRaceCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxRaceConejillo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBoxFlavorCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBoxFlavorDog, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblRegisterMake)
                                .addGap(80, 80, 80)
                                .addComponent(lblRegisterMake1)
                                .addGap(97, 97, 97)
                                .addComponent(lblRegisterMake2)
                                .addGap(70, 70, 70)
                                .addComponent(lblAnimal3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(493, 493, 493)
                                .addComponent(lblAnimal4)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAnimal2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnBackMenuEmployee)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduct)
                    .addComponent(radProductAccesory)
                    .addComponent(radProductToy)
                    .addComponent(radProductFood))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterMake)
                    .addComponent(lblRegisterMake1)
                    .addComponent(lblRegisterMake2)
                    .addComponent(lblAnimal3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnimal4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxMakeDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radProductFood1)
                    .addComponent(ComboBoxRaceDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxFlavorDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxRaceCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxMakeCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxFlavorCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radProductAccesory1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboBoxMakeConejillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboBoxRaceConejillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radProductToy1)))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimal2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnimal1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegisterMake3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxMakeCow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radProductFood2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxMakeHorse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radProductAccesory2))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radProductToy2)
                            .addComponent(ComboBoxMakePig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radProductToy3)
                            .addComponent(ComboBoxMakeChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(lblAnimal6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimal5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        lblAnimal8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal8.setText("Unidades:");

        lblAnimal9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal9.setText("Mascotas de casa:");

        ComboBoxAccesoryConejillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plato", "Jaula", "Caminadora" }));
        ComboBoxAccesoryConejillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAccesoryConejilloActionPerformed(evt);
            }
        });

        ComboBoxAccesoryCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Collar", "Placa", "Plato", "Peine", "Arena", "Arenero" }));
        ComboBoxAccesoryCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAccesoryCatActionPerformed(evt);
            }
        });

        ComboBoxAccesoryDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Collar", "Placa", "Plato", "Peine", "Cama" }));
        ComboBoxAccesoryDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAccesoryDogActionPerformed(evt);
            }
        });

        radProductToy5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductToy5.setText("Conejillo");
        radProductToy5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductToy5ActionPerformed(evt);
            }
        });

        radProductFood4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductFood4.setText("Perro");
        radProductFood4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductFood4ActionPerformed(evt);
            }
        });

        lblProduct1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblProduct1.setText("SECCION DE ACCESORIOS");

        radProductAccesory3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductAccesory3.setText("Gato");
        radProductAccesory3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductAccesory3ActionPerformed(evt);
            }
        });

        jLabel4.setText("$");

        lblAnimal10.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal10.setText("Valor a cancelar:");

        ComboBoxAccesoryFarm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebedero 2LT", "Bebedero 4LT" }));
        ComboBoxAccesoryFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAccesoryFarmActionPerformed(evt);
            }
        });

        lblRegisterMake4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRegisterMake4.setText("Producto:");

        jLabel6.setText("$");

        lblAnimal7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal7.setText("Valor a cancelar:");

        lblAnimal14.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal14.setText("Unidades:");

        lblAnimal15.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal15.setText("De granja:");

        lblRegisterMake5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblRegisterMake5.setText("Producto:");

        lblAnimal16.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal16.setText("Vaca/Caballo/Cerdo/Pollo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProduct1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblAnimal9)
                        .addGap(46, 46, 46)
                        .addComponent(lblRegisterMake5)
                        .addGap(80, 80, 80)
                        .addComponent(lblAnimal8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radProductToy5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(radProductAccesory3)
                                                .addComponent(radProductFood4))
                                            .addGap(21, 21, 21)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBoxAccesoryDog, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBoxAccesoryCat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ComboBoxAccesoryConejillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblAnimal10)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)))
                            .addGap(54, 54, 54)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSpinner16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAnimal15)
                                .addComponent(lblAnimal16)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblAnimal7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)))
                            .addGap(48, 48, 48)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lblRegisterMake4)
                                    .addGap(149, 149, 149))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(ComboBoxAccesoryFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAnimal14)
                                        .addComponent(jSpinner15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(95, 95, 95))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblProduct1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimal9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnimal8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterMake5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxAccesoryDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radProductFood4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(ComboBoxAccesoryCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radProductAccesory3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxAccesoryConejillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radProductToy5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSpinner14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimal10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAnimal15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblAnimal16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRegisterMake4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxAccesoryFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAnimal14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimal7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ComboBoxToyCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelota", "Hueso", "Bola de estambre" }));
        ComboBoxToyCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxToyCatActionPerformed(evt);
            }
        });

        radProductAccesory4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductAccesory4.setText("Gato");
        radProductAccesory4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductAccesory4ActionPerformed(evt);
            }
        });

        lblProduct2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblProduct2.setText("SECCION DE JUGUETES");

        lblAnimal11.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal11.setText("Valor a cancelar:");

        radProductFood5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radProductFood5.setText("Perro");
        radProductFood5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProductFood5ActionPerformed(evt);
            }
        });

        jLabel5.setText("$");

        lblAnimal12.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal12.setText("Unidades:");

        lblAnimal13.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblAnimal13.setText("Mascotas de casa:");

        ComboBoxToyDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelota", "Cuerda", "Huesito", "Pollo chillón" }));
        ComboBoxToyDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxToyDogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProduct2))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(lblAnimal13)
                            .addGap(183, 183, 183)
                            .addComponent(lblAnimal12))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radProductAccesory4)
                                        .addComponent(radProductFood5))
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ComboBoxToyDog, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBoxToyCat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSpinner17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSpinner19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(lblAnimal11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jSpinner19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblProduct2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnimal13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnimal12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxToyDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radProductFood5))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxToyCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radProductAccesory4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnimal11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
    
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void radProductAccesoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductAccesoryActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductAccesoryActionPerformed

    private void radProductFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductFoodActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductFoodActionPerformed

    private void btnBackMenuEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMenuEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMenuEmployeeActionPerformed

    private void radProductToyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductToyActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductToyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void ComboBoxMakeDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMakeDogActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMakeDogActionPerformed

    private void radProductToy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductToy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductToy1ActionPerformed

    private void radProductFood1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductFood1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductFood1ActionPerformed

    private void radProductAccesory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductAccesory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductAccesory1ActionPerformed

    private void radProductToy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductToy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductToy2ActionPerformed

    private void radProductFood2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductFood2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductFood2ActionPerformed

    private void radProductAccesory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductAccesory2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductAccesory2ActionPerformed

    private void ComboBoxMakeConejilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMakeConejilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMakeConejilloActionPerformed

    private void ComboBoxMakeCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMakeCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMakeCatActionPerformed

    private void ComboBoxRaceConejilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRaceConejilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRaceConejilloActionPerformed

    private void ComboBoxRaceCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRaceCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRaceCatActionPerformed

    private void ComboBoxRaceDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRaceDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRaceDogActionPerformed

    private void ComboBoxFlavorCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFlavorCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxFlavorCatActionPerformed

    private void ComboBoxFlavorDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFlavorDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxFlavorDogActionPerformed

    private void ComboBoxMakePigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMakePigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMakePigActionPerformed

    private void ComboBoxMakeChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMakeChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMakeChickenActionPerformed

    private void ComboBoxMakeCowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMakeCowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMakeCowActionPerformed

    private void ComboBoxMakeHorseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMakeHorseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMakeHorseActionPerformed

    private void ComboBoxAccesoryConejilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAccesoryConejilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAccesoryConejilloActionPerformed

    private void ComboBoxAccesoryCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAccesoryCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAccesoryCatActionPerformed

    private void ComboBoxAccesoryDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAccesoryDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAccesoryDogActionPerformed

    private void radProductToy5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductToy5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductToy5ActionPerformed

    private void radProductFood4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductFood4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductFood4ActionPerformed

    private void radProductAccesory3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductAccesory3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductAccesory3ActionPerformed

    private void ComboBoxToyCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxToyCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxToyCatActionPerformed

    private void radProductAccesory4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductAccesory4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductAccesory4ActionPerformed

    private void radProductFood5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProductFood5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radProductFood5ActionPerformed

    private void ComboBoxToyDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxToyDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxToyDogActionPerformed

    private void ComboBoxAccesoryFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAccesoryFarmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAccesoryFarmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEmployeeAddProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxAccesoryCat;
    private javax.swing.JComboBox<String> ComboBoxAccesoryConejillo;
    private javax.swing.JComboBox<String> ComboBoxAccesoryDog;
    private javax.swing.JComboBox<String> ComboBoxAccesoryFarm;
    private javax.swing.JComboBox<String> ComboBoxFlavorCat;
    private javax.swing.JComboBox<String> ComboBoxFlavorDog;
    private javax.swing.JComboBox<String> ComboBoxMakeCat;
    private javax.swing.JComboBox<String> ComboBoxMakeChicken;
    private javax.swing.JComboBox<String> ComboBoxMakeConejillo;
    private javax.swing.JComboBox<String> ComboBoxMakeCow;
    private javax.swing.JComboBox<String> ComboBoxMakeDog;
    private javax.swing.JComboBox<String> ComboBoxMakeHorse;
    private javax.swing.JComboBox<String> ComboBoxMakePig;
    private javax.swing.JComboBox<String> ComboBoxRaceCat;
    private javax.swing.JComboBox<String> ComboBoxRaceConejillo;
    private javax.swing.JComboBox<String> ComboBoxRaceDog;
    private javax.swing.JComboBox<String> ComboBoxToyCat;
    private javax.swing.JComboBox<String> ComboBoxToyDog;
    private javax.swing.JButton btnBackMenuEmployee;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner15;
    private javax.swing.JSpinner jSpinner16;
    private javax.swing.JSpinner jSpinner17;
    private javax.swing.JSpinner jSpinner19;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JLabel lblAnimal;
    private javax.swing.JLabel lblAnimal1;
    private javax.swing.JLabel lblAnimal10;
    private javax.swing.JLabel lblAnimal11;
    private javax.swing.JLabel lblAnimal12;
    private javax.swing.JLabel lblAnimal13;
    private javax.swing.JLabel lblAnimal14;
    private javax.swing.JLabel lblAnimal15;
    private javax.swing.JLabel lblAnimal16;
    private javax.swing.JLabel lblAnimal2;
    private javax.swing.JLabel lblAnimal3;
    private javax.swing.JLabel lblAnimal4;
    private javax.swing.JLabel lblAnimal5;
    private javax.swing.JLabel lblAnimal6;
    private javax.swing.JLabel lblAnimal7;
    private javax.swing.JLabel lblAnimal8;
    private javax.swing.JLabel lblAnimal9;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProduct1;
    private javax.swing.JLabel lblProduct2;
    private javax.swing.JLabel lblRegisterMake;
    private javax.swing.JLabel lblRegisterMake1;
    private javax.swing.JLabel lblRegisterMake2;
    private javax.swing.JLabel lblRegisterMake3;
    private javax.swing.JLabel lblRegisterMake4;
    private javax.swing.JLabel lblRegisterMake5;
    private javax.swing.ButtonGroup productButtonGroup;
    private javax.swing.JRadioButton radProductAccesory;
    private javax.swing.JRadioButton radProductAccesory1;
    private javax.swing.JRadioButton radProductAccesory2;
    private javax.swing.JRadioButton radProductAccesory3;
    private javax.swing.JRadioButton radProductAccesory4;
    private javax.swing.JRadioButton radProductFood;
    private javax.swing.JRadioButton radProductFood1;
    private javax.swing.JRadioButton radProductFood2;
    private javax.swing.JRadioButton radProductFood4;
    private javax.swing.JRadioButton radProductFood5;
    private javax.swing.JRadioButton radProductToy;
    private javax.swing.JRadioButton radProductToy1;
    private javax.swing.JRadioButton radProductToy2;
    private javax.swing.JRadioButton radProductToy3;
    private javax.swing.JRadioButton radProductToy5;
    // End of variables declaration//GEN-END:variables
}
