package ec.edu.espe.petshopinventorycontrol.view;

import com.mongodb.client.FindIterable;
import javax.swing.ImageIcon;
import java.awt.Image;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import org.bson.Document;
import ec.edu.espe.petshopinventorycontrol.controller.DataManager;
import ec.edu.espe.petshopinventorycontrol.view.FrmManagerMenu;
import java.util.ArrayList;
import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan Gudino, KNOWLEDGE ENCAPSULATE, @ESPE
 */
public class FrmManagerModifyInventory extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmManagerModifyInventory.class.getName());

    /**
     * Creates new form NewJFrame1
     */
    public FrmManagerModifyInventory() {
        initComponents();
        rbttnPriceModifyProduct.addActionListener(e -> {
            txtNewPriceModifyProduct.setEnabled(true);
            txtNewStockModifyProduct.setEnabled(false);
        });

        rbttnStockModifyProduct.addActionListener(e -> {
            txtNewPriceModifyProduct.setEnabled(false);
            txtNewStockModifyProduct.setEnabled(true);
        });

    }

    private void loadAllProducts() {
        try {
            MongoDatabase db = DataManager.getDB();
            MongoCollection<Document> coll = db.getCollection("productos");

            List<Document> products = coll.find().into(new ArrayList<>());

            DefaultTableModel model = (DefaultTableModel) tblModifyProduct.getModel();
            model.setRowCount(0);

            for (Document doc : products) {
                model.addRow(new Object[]{
                    doc.getString("id"),
                    doc.getString("typeAnimal"),
                    doc.getString("typeProduct"),
                    doc.getString("species"),
                    doc.getString("brand"),
                    doc.getDouble("price"),
                    doc.getInteger("stock")
                });
            }

        } catch (Exception e) {
            System.out.println("Error al cargar productos: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bttnUpdateModifyProduct = new javax.swing.JButton();
        bttnModifyProduct = new javax.swing.JButton();
        bttnExitModifyProduct1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblModifyProduct = new javax.swing.JTable();
        jLabel12ModifyProduct = new javax.swing.JLabel();
        txtIdModifyProduct = new javax.swing.JTextField();
        jLabel4ModifyProduct = new javax.swing.JLabel();
        rbttnPriceModifyProduct = new javax.swing.JRadioButton();
        rbttnStockModifyProduct = new javax.swing.JRadioButton();
        jLabel6ModifyProduct = new javax.swing.JLabel();
        jLabel5ModifyProduct = new javax.swing.JLabel();
        txtNewPriceModifyProduct = new javax.swing.JTextField();
        txtNewStockModifyProduct = new javax.swing.JTextField();
        jLabel7ModifyProduct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 119));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFICAR PRODUCTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 119));

        bttnUpdateModifyProduct.setText("Actualizar");
        bttnUpdateModifyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUpdateModifyProductActionPerformed(evt);
            }
        });

        bttnModifyProduct.setText("Modificar");
        bttnModifyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnModifyProductActionPerformed(evt);
            }
        });

        bttnExitModifyProduct1.setText("Salir ");
        bttnExitModifyProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExitModifyProduct1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(bttnModifyProduct)
                .addGap(48, 48, 48)
                .addComponent(bttnUpdateModifyProduct)
                .addGap(41, 41, 41)
                .addComponent(bttnExitModifyProduct1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnUpdateModifyProduct)
                    .addComponent(bttnModifyProduct)
                    .addComponent(bttnExitModifyProduct1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tblModifyProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tipo de animal", "Producto", "Animal", "Marca ", "Precio", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tblModifyProduct);

        jLabel12ModifyProduct.setText("Ingresa el codigo del producto a ser modificado:");

        jLabel4ModifyProduct.setText("¿Que campo deseas modificar?");

        rbttnPriceModifyProduct.setText("PRECIO");

        rbttnStockModifyProduct.setText("STOCK");

        jLabel6ModifyProduct.setText("Ingresa nuevo precio: ");

        jLabel5ModifyProduct.setText("Ingresa nuevo Stock:");

        jLabel7ModifyProduct.setText("$");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel12ModifyProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdModifyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6ModifyProduct)
                                            .addComponent(jLabel5ModifyProduct))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNewPriceModifyProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                            .addComponent(txtNewStockModifyProduct))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7ModifyProduct))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbttnPriceModifyProduct)
                                            .addComponent(jLabel4ModifyProduct))
                                        .addGap(46, 46, 46)
                                        .addComponent(rbttnStockModifyProduct))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12ModifyProduct)
                    .addComponent(txtIdModifyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4ModifyProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbttnPriceModifyProduct)
                    .addComponent(rbttnStockModifyProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6ModifyProduct)
                    .addComponent(txtNewPriceModifyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7ModifyProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5ModifyProduct)
                    .addComponent(txtNewStockModifyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnUpdateModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUpdateModifyProductActionPerformed
        // TODO add your handling code here:
        String idFilter = txtIdModifyProduct.getText().trim();

        try {
            MongoDatabase db = DataManager.getDB();
            MongoCollection<Document> coll = db.getCollection("productos");

            DefaultTableModel model = (DefaultTableModel) tblModifyProduct.getModel();
            model.setRowCount(0);

            FindIterable<Document> results;

            if (idFilter.isEmpty()) {
                results = coll.find();
            } else {
                results = coll.find(Filters.eq("id", idFilter));
            }

            for (Document doc : results) {
                model.addRow(new Object[]{
                    doc.getString("id"),
                    doc.getString("typeAnimal"),
                    doc.getString("typeProduct"),
                    doc.getString("species"),
                    doc.getString("brand"),
                    doc.getDouble("price"),
                    doc.getInteger("stock")
                });
            }

        } catch (Exception e) {
            System.out.println("Error al actualizar tabla: " + e.getMessage());
        }
    }//GEN-LAST:event_bttnUpdateModifyProductActionPerformed

    private void bttnModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnModifyProductActionPerformed
        // TODO add your handling code here:

        int selected = tblModifyProduct.getSelectedRow();

        if (selected == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla.");
            return;
        }

        String id = tblModifyProduct.getValueAt(selected, 0).toString();

        try {
            MongoDatabase db = DataManager.getDB();
            MongoCollection<Document> coll = db.getCollection("productos");

            Document updateDoc = new Document();

            if (rbttnPriceModifyProduct.isSelected()) {
                double newPrice = Double.parseDouble(txtNewPriceModifyProduct.getText());
                updateDoc.append("price", newPrice);
            }

            if (rbttnStockModifyProduct.isSelected()) {
                int newStock = Integer.parseInt(txtNewStockModifyProduct.getText());
                updateDoc.append("stock", newStock);
            }

            coll.updateOne(Filters.eq("id", id), new Document("$set", updateDoc));

            JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");

            bttnUpdateModifyProductActionPerformed(null); // refrescar tabla

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage());
        }

    }//GEN-LAST:event_bttnModifyProductActionPerformed

    private void bttnExitModifyProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExitModifyProduct1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FrmManagerMenu menu = new FrmManagerMenu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);


    }//GEN-LAST:event_bttnExitModifyProduct1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnExitModifyProduct1;
    private javax.swing.JButton bttnModifyProduct;
    private javax.swing.JButton bttnUpdateModifyProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12ModifyProduct;
    private javax.swing.JLabel jLabel4ModifyProduct;
    private javax.swing.JLabel jLabel5ModifyProduct;
    private javax.swing.JLabel jLabel6ModifyProduct;
    private javax.swing.JLabel jLabel7ModifyProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbttnPriceModifyProduct;
    private javax.swing.JRadioButton rbttnStockModifyProduct;
    private javax.swing.JTable tblModifyProduct;
    private javax.swing.JTextField txtIdModifyProduct;
    private javax.swing.JTextField txtNewPriceModifyProduct;
    private javax.swing.JTextField txtNewStockModifyProduct;
    // End of variables declaration//GEN-END:variables
}
