package ec.edu.espe.petshopinventorycontrol.view;    

import ec.edu.espe.petshopinventorycontrol.controller.ProductInventoryController;
import ec.edu.espe.petshopinventorycontrol.model.PurchaseProduct;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FrmSummaryProduct extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private List<PurchaseProduct> products = new ArrayList<>();

    private FrmAddProduct addProductForm;
    
    public FrmSummaryProduct() {
        
        this.addProductForm = addProductForm;
        initComponents();
        initTable();
         
    }



    FrmSummaryProduct(FrmAddProduct aThis) {
        this();                 
        this.addProductForm = aThis;
    }

    private void initTable() {
        tableModel = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Tipo", "Animal", "Cantidad", "Costo Total"}, 0
        );
        tblAddProduct.setModel(tableModel);
    }

    public void addProduct(PurchaseProduct product) {
        // Guardamos los datos tal cual, sin convertir a String
        tableModel.addRow(new Object[]{
                product.getProductId(),
                product.getProductName(),
                product.getProductType(),
                product.getAnimal(),
                product.getQuantity(),
                product.getTotalCost()  // <-- Mantener Double
        });

        products.add(product);

        updateTotals();
    }

    private void updateTotals() {
        double total = 0.0;

        for (int i = 0; i < tableModel.getRowCount(); i++) {
            Object value = tableModel.getValueAt(i, 5); // columna 5 = totalCost
            double cost;

            if (value instanceof Double) {
                cost = (Double) value;
            } else {
                // Reeplace toString
                cost = Double.parseDouble(value.toString().replace(",", ""));
            }

            total += cost;
        }

        lblTotalSell.setText(String.format("TOTAL: %.2f", total));
    }


    private void openAddProductWindow() {
    
    FrmAddProduct addProductForm = new FrmAddProduct(); 
    addProductForm.setLocationRelativeTo(this);
    addProductForm.setVisible(true);
    this.dispose();  
    
}
   
    private void returnToAddProduct() {
    if (addProductForm != null) {
        addProductForm.setVisible(true);
    }
    this.dispose();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAddProduct = new javax.swing.JTable();
        lblTotalSell = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAddProductToSell = new javax.swing.JMenu();
        menuItemAddProduct = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 119));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESUMEN DE COMPRA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(255, 255, 255))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 119));

        btnEdit.setText("Editar");

        btnDelete.setText("Eliminar");

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnEdit)
                .addGap(62, 62, 62)
                .addComponent(btnDelete)
                .addGap(73, 73, 73)
                .addComponent(btnSave)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addGap(15, 15, 15))
        );

        tblAddProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Tipo", "Animal", "Cantidad comprada", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblAddProduct);

        lblTotalSell.setText("$ 0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 473, Short.MAX_VALUE)
                .addComponent(lblTotalSell, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblTotalSell, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        menuAddProductToSell.setText("Regresar");
        menuAddProductToSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProductToSellActionPerformed(evt);
            }
        });

        menuItemAddProduct.setText("Agregar producto");
        menuItemAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddProductActionPerformed(evt);
            }
        });
        menuAddProductToSell.add(menuItemAddProduct);

        jMenuItem2.setText("Imprimir ");
        menuAddProductToSell.add(jMenuItem2);

        jMenuBar1.add(menuAddProductToSell);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    if (products.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "No hay productos para guardar",
                "Tabla vacía",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    ProductInventoryController controller =
            new ProductInventoryController();

    controller.saveFromTable(products);

    JOptionPane.showMessageDialog(this,
            "Productos guardados correctamente",
            "MongoDB",
            JOptionPane.INFORMATION_MESSAGE);

    products.clear();
    tableModel.setRowCount(0);        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void menuAddProductToSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProductToSellActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_menuAddProductToSellActionPerformed

    private void menuItemAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddProductActionPerformed

        System.out.println(addProductForm);
        
        addProductForm.setLocationRelativeTo(this);
        addProductForm.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAddProductActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalSell;
    private javax.swing.JMenu menuAddProductToSell;
    private javax.swing.JMenuItem menuItemAddProduct;
    private javax.swing.JTable tblAddProduct;
    // End of variables declaration//GEN-END:variables
}

